default: &default
  adapter: postgresql
  port: 5432
  encoding: utf8
  max_connections: 5

development:
  <<: *default
  database: smart_auth_example_dev
  user: rails
  password: rails

test:
  <<: *default
  database: smart_auth_example_test
  user: rails
  password: rails
